<?php

/**
 * Implements hook_services_resources().
 */
function services_backup_migrate_services_resources() {
  $resources = array();

  $resources['backup_migrate'] = array(
    'index' => array(
      'callback' => 'backup_migrate_index',
      'access arguments' => array('administer nodes'),
      'access arguments append' => FALSE,
    ),
    'create' => array(
      'callback' => 'backup_migrate_quickbackup_create',
      'args' => array(
        array(
          'name' => 'backup_migrate',
          'optional' => FALSE,
          'source' => 'data',
          'description' => 'Quick Backup',
          'type' => 'array',
        ),
      ),
      'access callback' => 'backup_migrate_resource_access',
      'access arguments' => array('create'),
      'access arguments append' => TRUE,
    ),
  );

  $resources['backup_migrate_destination'] = array(
    'index' => array(
      'callback' => 'backup_migrate_destination_index',
      'access arguments' => array('administer nodes'),
      'access arguments append' => FALSE,
    ),
    'update' => array(
      'callback' => 'backup_migrate_backup_restore',
      'args' => array(
        array(
          'name' => 'file_id',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
          'description' => 'The file_id of file.',
        ),
        array(
          'name' => 'destination_id',
          'optional' => FALSE,
          'source' => array('path' => 1),
          'type' => 'string',
          'description' => 'The destination id of the display files',
        ),
      ),
      'access callback' => 'backup_migrate_destination_resource_access',
      'access arguments' => array('restore'),
      'access arguments append' => TRUE,
    ),
    'delete' => array(
      'callback' => 'backup_migrate_backup_delete',
      'args' => array(
        array(
          'name' => 'file_id',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
          'description' => 'The file_id of file.',
        ),
        array(
          'name' => 'destination_id',
          'optional' => FALSE,
          'source' => array('path' => 1),
          'type' => 'string',
          'description' => 'The destination id of the display files',
        ),
      ),
      'access callback' => 'backup_migrate_destination_resource_access',
      'access arguments' => array('delete'),
      'access arguments append' => TRUE,
    ),
    'retrieve' => array(
      'callback' => 'backup_migrate_destination_display_files',
      'args' => array(
        array(
          'name' => 'destination_id',
          'optional' => FALSE,
          'source' => array('path' => 0),
          'type' => 'string',
          'description' => 'The destination id of the display files',
        ),
      ),
      'access callback' => 'backup_migrate_destination_resource_access',
      'access arguments' => array('view'),
      'access arguments append' => TRUE,
    ),
  );

  return $resources;
}


/**
 * Gets access rules.
 *
 * @param string $op
 *  $op - Permission requested.
 * @return Boolean
 *  Boolean TRUE if the current user has the requested permission.
 */
function backup_migrate_resource_access($op = 'view', $args = array()) {
  switch ($op) {
    case 'view':
      return user_access('access backup and migrate');
      break;
    case 'create':
      return user_access('perform backup');
      break;
  }
}

/**
 * Returns list of available Sources, Destinations and Profiles . 
 *
 * @return
 *   list of available Sources, Destinations and Profiles.
 */
function backup_migrate_index() { 
  module_load_include('inc', 'backup_migrate', 'includes/destinations');
  module_load_include('inc', 'backup_migrate', 'includes/profiles');
  $list = array();
  $list['source_list'] = _backup_migrate_get_destination_form_item_options('source');
  $destinations = _backup_migrate_get_destination_form_item_options('manual backup');
  if ($destinations) {
    foreach ($destinations as $key => $val) {
      if ($key != 'download') {
        $opt[$key] = $val;
      }
    }
    $list['destination_list'] = $opt;
  }
  $list['profile_list'] = _backup_migrate_get_profile_form_item_options();
  return $list;
}

function backup_migrate_quickbackup_create($quick_backup) { 
  module_load_include('inc', 'backup_migrate', 'includes/profiles');
  module_load_include('inc', 'backup_migrate', 'includes/destinations');
    
  // For a quick backup use the default settings.
  $settings = _backup_migrate_profile_saved_default_profile($quick_backup['profile_id']);

  // Set the destination to the one chosen in the pulldown.
  $settings->destination_id = $quick_backup['destination_id'];
  $settings->source_id = $quick_backup['source_id'];

  // Save the settings for next time.
  variable_set("backup_migrate_source_id", $quick_backup['source_id']);
  variable_set("backup_migrate_destination_id", $quick_backup['destination_id']);
  variable_set("backup_migrate_profile_id", $quick_backup['profile_id']);
    
  // Do the backup.
  $backup_info = backup_migrate_perform_backup($settings); 
    
  $file = $backup_info->file_info['filename'];
  $dest = $settings->get_destination_name();
  $source = $settings->get_source_name();
  $time = timer_stop('backup_migrate_backup');
  $action = !empty($settings->performed_action) ? $settings->performed_action : '';
  //@todo : replace with t().
  $backup_message['backup_file'] = 'Default Database backed up successfully to '.$file.' in destination Filer Directory in '.$time['time'].' ms. '. $action;
  return $backup_message;
}

/**
 * Gets access rules.
 *
 * @param string $op
 *  $op - Permission requested.
 * @return Boolean
 *  Boolean TRUE if the current user has the requested permission.
 */
function backup_migrate_destination_resource_access($op = 'view', $args = array()) {
watchdog('op', $op);
  switch ($op) {
    case 'view':
      return user_access('access backup files');
      break;
    case 'restore':
     return user_access('restore from backup');
     break;
    case 'delete':
     return user_access('access backup files');
     break;
  }
}

/**
 * Returns list of destinations. 
 *
 * @return
 *   list of destinations.
 */

function backup_migrate_destination_index() { 
  module_load_include('inc', 'backup_migrate', 'includes/crud');
  $class = new backup_migrate_destination;

  if ($type = backup_migrate_crud_type_load('destination')) {
    $items = $class->all_items();
    $rows = array();
    foreach ($items as $item) {
      if ($row = $item->get_list_row()) { 
        $row['id'] = $item->destination_id;
        $rows[] = $row;
      }
    } 
    return $rows;
  } 
}

/**
 * Returns backup files in the given destination.
 * @param $destination_id
 *  $destination_id - destination_id (manual, scheduled, etc).
 * @return
 *   list of destination files.
 */
function backup_migrate_destination_display_files($destination_id = NULL) { 
  module_load_include('inc', 'backup_migrate', 'includes/destinations'); 
  $rows = $sort = array();

  if ($destination = backup_migrate_get_destination($destination_id)) {
    $files = $destination->list_files();
    foreach ((array)$files as $file) {
      $info = $file->info();
      // Show only files that can be restored from.
      if ($file->is_recognized_type()) {
        $sort[] = $info['filetime'];
        $rows[] = array(
          'filename' => check_plain($info['filename']),
          'date_time' => format_date($info['filetime'], 'small'),
          'age' => format_interval(time() - $info['filetime'], 1),
          'size' => format_size($info['filesize']),
          'file_id' => $file->file_id(),
        );
      }
    }

    array_multisort($sort, SORT_DESC, $rows);

    if (count($rows) > 0) {
      return $rows;
    }
    else {
      return services_error(t('There are no backup files available.'), 406, null);
    }
  }
}


/**
 * Returns success message on restore or delete else service error.
 * @param $data
 *  $data - restore or delete data (like filename, destination_id, etc..).
 * @return
 *   success message or service error.
 */
function backup_migrate_backup_restore($file, $destination_id) {
  module_load_include('inc', 'backup_migrate', 'includes/destinations'); 

  if (!backup_migrate_destination_file_exists($destination_id, $file)) { 
    return services_error(t('File @file does not exists at @destination destination ', array('@file' => $file, '@destination' => $destination_id)), 404, null);
  }

  if (!backup_migrate_perform_restore($destination_id, $file)) {
    return services_error(t('Failed to restore from file @file', array('@file' => $file)), 406, null);
  }
  else {
    $message['backup_migrate'] = array(
      'message' => t('Restored file @file', array('@file' => $file)),
    );
  }
  return $message;
}

function backup_migrate_backup_delete($file, $destination_id) { 
  module_load_include('inc', 'backup_migrate', 'includes/destinations'); 

  if (!backup_migrate_destination_file_exists($destination_id, $file)) { 
    return services_error(t('File @file does not exists at @destination destination ', array('@file' => $file, '@destination' => $destination_id)), 404, null);
  }

  backup_migrate_destination_delete_file($destination_id, $file);
  $message['backup_migrate'] = array(
    'message' => t('Backup file @file deleted', array('@file' => $file)),
  );
  return $message;
}
